/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as FloorRouteImport } from './routes/floor'
import { Route as OpenapiDotjsonRouteImport } from './routes/openapi[.]json'
import { Route as SkillRouteImport } from './routes/skill'
import { Route as SkillDotjsonRouteImport } from './routes/skill[.]json'
import { Route as DotwellKnownSkillDotjsonRouteImport } from './routes/[.]well-known.skill[.]json'
import { Route as WatchIdRouteImport } from './routes/watch.$id'
import { Route as ApiV1IndexRouteImport } from './routes/api/v1/index'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorRoute = FloorRouteImport.update({
  id: '/floor',
  path: '/floor',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenapiDotjsonRoute = OpenapiDotjsonRouteImport.update({
  id: '/openapi.json',
  path: '/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillRoute = SkillRouteImport.update({
  id: '/skill',
  path: '/skill',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillDotjsonRoute = SkillDotjsonRouteImport.update({
  id: '/skill.json',
  path: '/skill.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownSkillDotjsonRoute =
  DotwellKnownSkillDotjsonRouteImport.update({
    id: '/.well-known/skill.json',
    path: '/.well-known/skill.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1IndexRoute = ApiV1IndexRouteImport.update({
  id: '/api/v1/',
  path: '/api/v1/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/floor': typeof FloorRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/skill': typeof SkillRoute
  '/skill.json': typeof SkillDotjsonRoute
  '/.well-known/skill.json': typeof DotwellKnownSkillDotjsonRoute
  '/watch/$id': typeof WatchIdRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/': typeof ApiV1IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/floor': typeof FloorRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/skill': typeof SkillRoute
  '/skill.json': typeof SkillDotjsonRoute
  '/.well-known/skill.json': typeof DotwellKnownSkillDotjsonRoute
  '/watch/$id': typeof WatchIdRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1': typeof ApiV1IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/floor': typeof FloorRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/skill': typeof SkillRoute
  '/skill.json': typeof SkillDotjsonRoute
  '/.well-known/skill.json': typeof DotwellKnownSkillDotjsonRoute
  '/watch/$id': typeof WatchIdRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/': typeof ApiV1IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/floor'
    | '/openapi.json'
    | '/skill'
    | '/skill.json'
    | '/.well-known/skill.json'
    | '/watch/$id'
    | '/api/v1/$'
    | '/api/v1/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/floor'
    | '/openapi.json'
    | '/skill'
    | '/skill.json'
    | '/.well-known/skill.json'
    | '/watch/$id'
    | '/api/v1/$'
    | '/api/v1'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/floor'
    | '/openapi.json'
    | '/skill'
    | '/skill.json'
    | '/.well-known/skill.json'
    | '/watch/$id'
    | '/api/v1/$'
    | '/api/v1/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  FloorRoute: typeof FloorRoute
  OpenapiDotjsonRoute: typeof OpenapiDotjsonRoute
  SkillRoute: typeof SkillRoute
  SkillDotjsonRoute: typeof SkillDotjsonRoute
  DotwellKnownSkillDotjsonRoute: typeof DotwellKnownSkillDotjsonRoute
  WatchIdRoute: typeof WatchIdRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiV1IndexRoute: typeof ApiV1IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floor': {
      id: '/floor'
      path: '/floor'
      fullPath: '/floor'
      preLoaderRoute: typeof FloorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openapi.json': {
      id: '/openapi.json'
      path: '/openapi.json'
      fullPath: '/openapi.json'
      preLoaderRoute: typeof OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill': {
      id: '/skill'
      path: '/skill'
      fullPath: '/skill'
      preLoaderRoute: typeof SkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill.json': {
      id: '/skill.json'
      path: '/skill.json'
      fullPath: '/skill.json'
      preLoaderRoute: typeof SkillDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/skill.json': {
      id: '/.well-known/skill.json'
      path: '/.well-known/skill.json'
      fullPath: '/.well-known/skill.json'
      preLoaderRoute: typeof DotwellKnownSkillDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/': {
      id: '/api/v1/'
      path: '/api/v1'
      fullPath: '/api/v1/'
      preLoaderRoute: typeof ApiV1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  FloorRoute: FloorRoute,
  OpenapiDotjsonRoute: OpenapiDotjsonRoute,
  SkillRoute: SkillRoute,
  SkillDotjsonRoute: SkillDotjsonRoute,
  DotwellKnownSkillDotjsonRoute: DotwellKnownSkillDotjsonRoute,
  WatchIdRoute: WatchIdRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiV1IndexRoute: ApiV1IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
